/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bk_tung_serial_ver1_SerialPort */

#ifndef _Included_bk_tung_serial_ver1_SerialPort
#define _Included_bk_tung_serial_ver1_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bk_tung_serial_ver1_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_bk_tung_serial_1ver1_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     bk_tung_serial_ver1_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bk_tung_serial_1ver1_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
